### ISSUE TITLE
Pull Request 제목에 Conventional Commit 자동 적용 및 검사

### ISSUE THREAD

**Issue by Eu4ng** [Eu4ng/test-github-actions#1]
## 선행 이슈

- https://github.com/Eu4ng/test-commitlint/issues/5#issuecomment-1909280190

## 개요

Pull Request 제목에 Conventional Commit 자동 적용 및 검사하는 GitHub Actions 작성하기

```yaml
name: Check Pull Request Title
on:
    pull_request:
        types: [opened, synchronize, edited]

jobs:
    check-pull-request-title:
        name: Check Pull Request Title
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Print Pull Request Title
              env:
                TITLE: ${{ github.event.pull_request.title }}
              run: echo The Title of your PR is $TITLE
```

![image](https://github.com/Eu4ng/test-github-actions/assets/59055049/b9e37302-8358-4218-925b-25293e5621fe)
